### ISSUE TITLE
Invalid default brightness, contrast, and possibly resolution

### ISSUE THREAD

**Issue by CMaiku** [mback2k/wiasane#15]
Thank you for writing this driver. It's just what I needed to set up my scanner for the network.

However, I'm having an issue where in both the native wia scanning (reached with NAPS2) and the windows fax and scan dialogs the brightness, contrast, and I believe, but am not certain the resolution, have invalid default values.

On first run, in the native wia scanning dialog, the default brightness was -1000, contrast was -1000, and resolution was 12800. I'm not certain, but I doubt my scanner (an Epson Perfection 1660 Photo) supports that high of a resolution. In the windows fax and scan dialog, the resolution was sensible at 300, but brightness and contrast are maxed out at -100 each. On subsequent scans, the default brightness for the native wia scanning dialog is now -334 and for the windows fax and scan is -33.

I looked at the open issues and wonder if this might be related to issue #6.

Please let me know if I can provide any further information and thanks again for writing this.

**Comment by mback2k** [comment]
This should already have been fixed by https://github.com/mback2k/wiasane/releases/tag/v0.1.1.9.
