### ISSUE TITLE
WIASane causes scanner to enter error state when scanning multiple documents via ADF

### ISSUE THREAD

**Issue by stevester91** [mback2k/wiasane#16]
O/S: Windows 8.1 64 bit
Scanner: Canon MX320 Multi-Function
Scanner Application: Windows Fax and Scan

While attempting to scan multiple documents using the ADF via wiasane and Windows Fax and Scan, the first page appears to scan properly however upon entry of the second page into the ADF (roughly half way) the scanning process stops and the scanner displays an error message saying to close the ADF hatch. Repeated this process multiple times using SaneTwain and the ADF functions perfectly whereas everytime I try to scan via wiasane it will always freeze as described above and never finish.

**Comment by mback2k** [comment]
Hello, sorry for the very long delay, but I just published a new version that might fix your problem. Please try [wiasane-v0.1.1.9-61-ge4c69e6.exe](https://wiasane.marc-hoersken.de/download/release/rev/e4c69e64c770fde21022999e5c2935e7a2bdbdef/196/wiasane-v0.1.1.9-61-ge4c69e6.exe). Thanks!

**Comment by mback2k** [comment]
This issue should be fixed by the newest release https://github.com/mback2k/wiasane/releases/tag/v0.1.2.10.
