### ISSUE TITLE
Installation breaks link to MSVCR90.dll

### ISSUE THREAD

**Issue by artistro08** [mback2k/wiasane#20]
Follows with an error "could not load entry point" on some programs. After re-installing the libraries, it works awesome. happens on Win 8.1

AWESOME driver btw.

**Comment by artistro08** [comment]
i should also add that it pops up with a dll error. can't remember what that one was. if I could reproduce it, i'll post more errors

**Comment by mback2k** [comment]
What do you mean by saying "breaks link to MSVCR90.dll"? Does it touch an existing file on your system during installation?

**Comment by artistro08** [comment]
Yes. Causing apps to not behave that uses that library to not work correctly

**Comment by mback2k** [comment]
I do not see how the installer could affect "MSVCR90.dll", since it only installs the following files to C:\Windows\system32\ if they are not present or older:
msvcp110.dll, msvcr110.dll, vccorlib110.dll

**Comment by mback2k** [comment]
18b36f8d3f2c5264e5e3dccba08404c5042bf2ff should make sure that other files are not touched.
