### ISSUE TITLE
hpaio:/net/ devices not in list. need to use device name explicitly

### ISSUE THREAD

**Issue by MikeQ123** [mback2k/wiasane#24]
Hi.
For some reason sane server does not enumerate hpaio:/net devices. 
I can see devices on sane server via scanimage -L . 
I can scan remotely via xsane if I use device name explicitly: xsane net:10.50.6.218:hpaio:/net/HP_LaserJet_Pro_MFP_M521dn?ip=10.166.203.1
But devices hpaio:/net/ are not in list in devsane.exe util. 
So I need to put device name explicitly to device list in devsane.exe 
I know - this is hplip\sane trouble, but it is possible to workaround it in wiasane/devsane.exe util.

**Comment by mback2k** [comment]
Hi, this seems to have been caused by a recent change in the hpaio code. Please see the following post:
http://comments.gmane.org/gmane.comp.printing.hplip.devel/462
You need to modify hpaio for now. But I might be able to add support for unlisted sane devices at some point

**Comment by MikeQ123** [comment]
thanks fo reply!
I use patch for hpaio and it working good!

**Comment by mback2k** [comment]
The next version of WiaSane will support unlisted scanners. Thanks for bringing this issue to my attention.

**Comment by mback2k** [comment]
Please try the following version: [wiasane-v0.1.1.9-39-gc8274bf.exe](https://wiasane.marc-hoersken.de/download/release/rev/c8274bffdddb076865fbcb0670372f1ebaa726a9/188/wiasane-v0.1.1.9-39-gc8274bf.exe)

**Comment by MikeQ123** [comment]
Hi Marc!

Thank you for your efforts!
I will test this version soon.
Can I get this version source? My brother made some modufications in
devsane.exe for batch scanner installing.

I have another two questions.
I trying to use your great tool on my Citrix Xenapp farm.
For scanning I use NAPS2 opensource tool. So some times, when I press
"Scan" button I get "Driver error" message. But after several seconds I
press "Scan" again and it works perfectly. How can I get log files or some
debug info?
The second question about autofeeder in HP M521 device. I always get
"Driver error" when I try use autofeeder in NAPS2. I use latest hpaio
drivers and plugin on my SANE server. I can collect some debyg info if
needed!

Thanks! Best regards!

Please try the following version: wiasane-v0.1.1.9-39-gc8274bf.exe
<https://wiasane.marc-hoersken.de/download/release/rev/c8274bffdddb076865fbcb0670372f1ebaa726a9/188/wiasane-v0.1.1.9-39-gc8274bf.exe>

—
Reply to this email directly or view it on GitHub
<https://github.com/mback2k/wiasane/issues/24#issuecomment-147598838>.
