### ISSUE TITLE
wiasane won't install on Win10

### ISSUE THREAD

**Issue by pmlopes** [mback2k/wiasane#25]
the VC runtime shows a conflict and aborts the install

**Comment by pmlopes** [comment]
With latest installer i can ignore the conflict and it installs

**Comment by mback2k** [comment]
Which version do you refer to as "latest installer"?

**Comment by pmlopes** [comment]
v0.1.1.9 with this one, when i get a popup with the message that it cannot remove the existing vc runtime if i choose ignore the installer continues to the end and completes the installation. When i start the wizard to setup the sane connection everything seems to be working fine too.

**Comment by mback2k** [comment]
Okay, I will have to setup a Win10 machine to test the VC compatibility.
