### ISSUE TITLE
While installing you need to disable windows firewall

### ISSUE THREAD

**Issue by kuloshius** [mback2k/wiasane#31]
Host: Ubuntu 16.04
Scanner HP Laser Jet M1220 MFP
Guest: Windows 10

If windows firewall is not disabled during installation process - connection to server fails "connection closed by remote host"

Once you disable windows firewall - installation succeeds.

After setup is complete - windows firewall can be enabled again and it does not affect actual scanning process, everything is working fine.

**Comment by mback2k** [comment]
I am also using the Windows Firewall on Windows 10 and never experienced such an issue. Could you please provide more details about your network setup? Is the saned server on the same local network?
