### ISSUE TITLE
Keeps scanner awake

### ISSUE THREAD

**Issue by jimbolaya** [mback2k/wiasane#37]
I downloaded and tried wiasane-v0.1.2.10.

It worked fine for me with the exception that it kept the scanner awake. As long as my computer was on, the scanner light was on. 

I didn't really see any settings that I could change.

**Comment by mback2k** [comment]
Unfortunately there is not much that can be changed about this. Windows accesses the state of the WIA device every once in a while and of course the driver also connects to the SANEd server in order to check the device state. That is probably what keeps your scanner awake.
