### ISSUE TITLE
Scanner session initialization failed

### ISSUE THREAD

**Issue by Sztoppolino** [mback2k/wiasane#41]
Hi!

I try to add a network scanner with WiaSane, but I can't do it, because I get a message:  

"Scanner session initialization failed."

My server is an OpenWRT router. I installed the sane-hs2p, sane-frontends, and my printer's driver (sane-xerox_mfp). I enabled uHTTPd service. That's work with on port 80.

Before I enabled the uHTTPd service, the WiaSane couldn't establish the connecton, but after I enabled the sevice, the program probably established the connection, because it didn't give me "Scanner session connect failed" error message, just "Scanner session initialization failed", so this problem it's probably another problem.
 
What's the solution?

**Comment by shanemeagher** [comment]
@Sztoppolino following the instructions on the [SaneOverNetwork](https://wiki.debian.org/SaneOverNetwork#Troubleshooting) Debian Wiki solved this issue for me.

When I looked at the saned.socket service logs on my server (RaspberryPiB+ running Debian Stretch), I was getting the following warning each time I tried tried to connect during WiaSane setup:

`saned.socket: Too many incoming connections (1), dropping connection.`

Changing the MaxConnections to 64 (I didn't try 2) as described and restarting server allowed me to connect (from Win10 x64 Version 10.0.17763 Build 17763) and select the scanner.

Quote from Debian Wiki [SaneOverNetwork](https://wiki.debian.org/SaneOverNetwork#Troubleshooting):
> If you have trouble connecting multiple computers to the server, systemctl status saned.socket might show:
> 
> saned.socket: Too many incoming connections (1), dropping connection.
> This is a [known bug](https://bugs.debian.org/850649) in the systemd unit. For a workaround on jessie or stretch:
> 
> cp /lib/systemd/system/saned.socket /etc/systemd/system/saned.socket.
> 
> Edit and replace MaxConnections=1 with MaxConnections=64.
> 
> systemctl daemon-reload.
> 
> [On stretch](https://manpages.debian.org/man/systemctl) it is probably more convenient to do:
> 
> systemctl edit --full saned.socket.

@mback2k Is there a reason the WiaSane driver would make more than 1 connection at a time?

**Comment by mback2k** [comment]
@shanemeagher Thanks for your answer. And yes, Windows queries all devices regularly and this results in an additional temporary connection to the scanner / saned daemon.

**Comment by shanemeagher** [comment]
Thanks. That makes sense.
Forgot to mention that this was with latest release (v0.1.2.10) but I think it shouldn't make a difference.
